include: package:flutter_lints/flutter.yaml

# Additional rules you can customize
linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false