import 'package:cloud_firestore/cloud_firestore.dart';

/// Represents a study task with details about estimated time, priority, and completion status.
///
/// Tasks are generated by AI from syllabus content and stored in Firestore under:
/// `users/{userId}/courses/{courseId}/tasks/{taskId}`
///
/// The `courseId` field determines which course this task belongs to.
/// Use 'planner-global' for general planner tasks not tied to a specific course.
class TaskModel {
  /// Firestore document ID. Null for new tasks not yet saved.
  final String? id;
  
  /// Short task title (e.g., "Read Chapter 3: CPU Architecture")
  final String title;
  
  /// Detailed task description from AI generation
  final String description;
  
  /// Estimated time to complete in minutes (used for scheduling)
  final int estimatedMinutes;
  
  /// Week identifier (e.g., "Week 1", "Week 2") from syllabus
  final String week;
  
  /// Priority level: "low", "medium", or "high"
  final String priority;
  
  /// Reference to parent course ID, or 'planner-global' for general tasks
  final String courseId;
  
  /// Whether the task has been marked complete by the user
  final bool isCompleted;
  
  /// Timestamp when task was created (server timestamp from Firestore)
  final DateTime? createdAt;
  
  /// Optional due date for the task
  final DateTime? dueDate;
  
  /// Legacy field: estimated hours (prefer estimatedMinutes)
  final int estimatedHours;

  TaskModel({
    this.id,
    required this.title,
    required this.description,
    required this.estimatedMinutes,
    required this.week,
    required this.priority,
    required this.courseId,
    this.isCompleted = false,
    this.createdAt,
    this.dueDate,
    this.estimatedHours = 1,
  });

  /// Helper to safely parse minutes from dynamic JSON values
  static int _parseMinutes(dynamic value) {
    if (value is int) return value;
    if (value is String) {
      final parsed = int.tryParse(value);
      if (parsed != null) return parsed;
    }
    return 60; // Default: 1 hour
  }

  /// Deserializes a TaskModel from Firestore JSON data.
  /// Handles missing fields with sensible defaults.
  factory TaskModel.fromJson(Map<String, dynamic> json) {
    DateTime? parsedCreatedAt;
    if (json['createdAt'] != null) {
      if (json['createdAt'] is Timestamp) {
        parsedCreatedAt = (json['createdAt'] as Timestamp).toDate();
      } else if (json['createdAt'] is String) {
        parsedCreatedAt = DateTime.parse(json['createdAt']);
      }
    }
    
    DateTime? parsedDueDate;
    if (json['dueDate'] != null) {
      if (json['dueDate'] is Timestamp) {
        parsedDueDate = (json['dueDate'] as Timestamp).toDate();
      } else if (json['dueDate'] is String) {
        parsedDueDate = DateTime.parse(json['dueDate']);
      }
    }
    
    return TaskModel(
      id: json['id']?.toString(),
      title: json['title']?.toString() ?? '',
      description: json['description']?.toString() ?? '',
      estimatedMinutes: _parseMinutes(json['estimatedMinutes']),
      week: json['week']?.toString() ?? '',
      priority: json['priority']?.toString() ?? 'medium',
      courseId: json['courseId']?.toString() ?? 'planner-global',
      isCompleted: json['isCompleted'] == true,
      createdAt: parsedCreatedAt,
      dueDate: parsedDueDate,
      estimatedHours: json['estimatedHours'] ?? 1,
    );
  }

  /// Serializes the TaskModel to JSON for Firestore storage.
  /// Omits null fields to reduce storage.
  Map<String, dynamic> toJson() {
    return {
      if (id != null) 'id': id,
      'title': title,
      'description': description,
      'estimatedMinutes': estimatedMinutes,
      'week': week,
      'priority': priority,
      'courseId': courseId,
      'isCompleted': isCompleted,
      if (createdAt != null) 'createdAt': createdAt!.toIso8601String(),
      if (dueDate != null) 'dueDate': dueDate!.toIso8601String(),
      'estimatedHours': estimatedHours,
    };
  }

  /// Creates a copy of this TaskModel with specified fields updated.
  /// Useful for updating task completion status or other properties.
  TaskModel copyWith({
    String? id,
    String? title,
    String? description,
    int? estimatedMinutes,
    String? week,
    String? priority,
    String? courseId,
    bool? isCompleted,
    DateTime? createdAt,
    DateTime? dueDate,
    int? estimatedHours,
  }) {
    return TaskModel(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      estimatedMinutes: estimatedMinutes ?? this.estimatedMinutes,
      week: week ?? this.week,
      priority: priority ?? this.priority,
      courseId: courseId ?? this.courseId,
      isCompleted: isCompleted ?? this.isCompleted,
      createdAt: createdAt ?? this.createdAt,
      dueDate: dueDate ?? this.dueDate,
      estimatedHours: estimatedHours ?? this.estimatedHours,
    );
  }
}