// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android; // Use android config as fallback
      case TargetPlatform.linux:
        return android; // Use android config as fallback
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCygPou-yM1-e1hA8X9efL-WG6kgodSYBU',
    authDomain: 'ai-planner-app-gcp.firebaseapp.com',
    projectId: 'ai-planner-app-gcp',
    storageBucket: 'ai-planner-app-gcp.firebasestorage.app',
    messagingSenderId: '1006584271656',
    appId: '1:1006584271656:web:4c42bc37302ca9f027761d',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx_fake_key_for_development',
    appId: '1:123456789:android:abcdef',
    messagingSenderId: '123456789',
    projectId: 'ai-planner-app',
    storageBucket: 'ai-planner-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx_fake_key_for_development',
    appId: '1:123456789:ios:abcdef',
    messagingSenderId: '123456789',
    projectId: 'ai-planner-app',
    storageBucket: 'ai-planner-app.appspot.com',
    iosBundleId: 'com.example.aiStudyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx_fake_key_for_development',
    appId: '1:123456789:ios:abcdef',
    messagingSenderId: '123456789',
    projectId: 'ai-planner-app',
    storageBucket: 'ai-planner-app.appspot.com',
    iosBundleId: 'com.example.aiStudyPlanner',
  );
}